apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
  serviceName: cassandra
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
        technology: cassandra
    spec:
      containers:
      - name: cassandra
        image: decomads/cassandra:2.2.16
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        resources:
          requests:
           cpu: "1000m"
           memory: 2Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "PID=$(pidof java) && kill $PID && while ps -p $PID > /dev/null; do sleep 1; done"]
        env:
          - name: MAX_HEAP_SIZE
            value: 1000M
          - name: HEAP_NEWSIZE
            value: 200M
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra.{{ .Release.Namespace }}.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "thesis-cassandra"
          - name: CASSANDRA_DC
            value: "thesis-cassandra-dc"
          - name: CASSANDRA_RACK
            value: "thesis-cassandra-rack"
          - name: CASSANDRA_AUTO_BOOTSTRAP
            value: "false"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /ready-probe.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
